---
title: "Homework 10"
author: "Colleen Yancey"
date: "March 28, 2018"
output: html_document
---

# Finishing our Batch Processing Code
Here I am finishing up the code we learned in class yesterday and will be playing around with the code to see if I can break the function
Below is the code that we worked on in class and finished today in lab:
```{r}
# Basic Code for batch processing
# 27 March 2018
# CEY

#########################################
# FUNCTION: FileBuilder
# create a set of random files for regression
# input: fileN= number of files to create, 
#       : fileFolder= name of folder for random files
#       : fileSize= c(min, max) number of rows in a file
#       : fileNA= number of average NA per column
# output: set of random files
#------------------------------------------

FileBuilder <- function(fileN=10,
                        fileFolder= "RandomFiles/",
                        fileSize= c(15,100),
                        fileNA=3){
  for (i in seq_len(fileN)){
    fileLength <- sample(fileSize[1]:fileSize[2], size=1)
    varX <-runif(fileLength) #random x values
    varY <-runif(fileLength) #random y values
    dF <- data.frame(varX,varY) #bind to data frame
    badVals <- rpois(n=1, lambda=fileNA) #number of bad values
    dF[sample(nrow(dF), size=badVals),1] <- NA
    dF[sample(nrow(dF), size=badVals),2] <- NA
    
#create a consecutive file name for this data fram
    fileLabel <- paste(fileFolder,
                       "ranFile",
                       formatC(i,
                               width=3,
                               format="d",
                               flag="0"),
                       ".csv", sep="")
# set up data file and incorporate time stampe and minimal metadata
    
write.table(cat("# Simulated random data file ",
                "for batch processing", "\n",
                "# timestamp: ", as.character(Sys.time()), "\n",
                "# CEY", "\n",
                "#------------------------", "\n",
                "\n",
                file=fileLabel,
                row.names="",
                col.names="",
                sep=""))

# add the data frame now
write.table(x=dF,
            file=fileLabel,
            sep=",",
            row.names=FALSE,
            append=TRUE)
} #close the for loop
} #close the function


#######################################################
# FUNCTION: regStats
# fit linear model, get regression stats
# input: 2-cloumn data frame
# output: slope, p-value, r2
#----------------------------------------------------

regStats <- function(d=NULL){
            if(is.null(d)) {
              xVar <- runif(10)
              yVar <- runif(10)
              d <- data.frame(xVar,yVar)
            }
  . <- lm(data=d, d[,2]~d[,1])
  . <- summary(.)
  statList <- list(Slope=.$coefficients[2,1],
                   pVal= .$coefficients[2,4],
                   r2=.$r.squared)
  return(statList)
} 
regStats()
#----------------------------------------
#Start body of porgram
library(TeachingDemos)
char2seed("Freezing March")

#--------------------------------
#Global Variables
fileFolder <- "RandomFiles/"
nFiles <- 100
fileOut <- "StatsSummary.csv"

#Create 100 Random data sets
FileBuilder(fileN=nFiles)

# Start of Lab Work
fileNames <- list.files(path=fileFolder)
dim(fileNames)

#Create data frame to hold file summary statistics
ID <- seq_along(fileNames)
fileName <- fileNames
slope <- rep(NA, nFiles)           
pVal <- rep(NA, nFiles)    
r2 <- rep(NA, nFiles)

statsOut <- data.frame(ID, fileName, slope, pVal, r2)

# batch [rpcess by looping through individual files
for (i in seq_along(fileNames)){
  data <- read.table(file=paste(fileFolder, fileNames[i], sep=""),
                     sep=",",
                     header=TRUE) # read in next data file
  dClean <- data[complete.cases(data),] #get clean cases
  . <- regStats(dClean) #pull regression stats from clean file
  statsOut[i, 3:5] <- unlist(.) #unlist, copy into last 3 columns
}

#set up output file and incorporate time stamp and minimal metadata
write.table(cat("# Summary stats for",
                "batch processing of regression model", "\n",
                " # timestamp: ", as.character(Sys.time()), "\n",
                "# CEY", "\n",
                "#------------------", "\n",
                "\n",
                file=fileOut,
                row.names="",
                col.names="",
                sep=""))
#now add a data frame
write.table(x=statsOut,
            file=fileOut,
            row.names= FALSE,
            col.names= TRUE,
            sep=",",
            append=TRUE)
```

### Altering NA values
Originally in the function above the number of NA values is set 3 (fileNA=3). If you mess around with this and increase it you will be increasing the number of NAs that can appear in the file. When I upped the NA value to 10, I only got 56 randomfiles. This makes it seem like the function can run, but incompletely. When I up it to 20 only 17 random files were made. The Error message that pops up says that you "cannot take a sample larger than the population when you 'replace=FALSE'. This error occurs during the for loop, all the code before it runs fine. Basically, what I think this means is that it is all being randomly run in a loop and there is a chance that you will get more NAs than your columns (thus being greater than the population you created, and we created a population bwteen (15, 100). There is still a chance that these NA's do not randomly get inserted to nullify a file and that is why you get a few random files. Basically this shows us that you can not have a fileNA greater than your population. If we put the NA value between the row min and max then eventually you will get more NAs (on average) than a column. Adding so many NAs makes it hard for the model to work with because there aren't any numbers. 

### Altering Row values
Decreasing Row vlaues pretty much does the same thing as increasing NA values. If you shrink the rows, that means there is a chance of having more NAs for resasons stated above. Once again, this upsets the model once again because there aren't enough numbers to work with and you get the same error.


